.PHONY: clean All

All:
	@echo "----------Building project:[ C__PROJECT - Debug ]----------"
	@"$(MAKE)" -f  "C__PROJECT.mk"
clean:
	@echo "----------Cleaning project:[ C__PROJECT - Debug ]----------"
	@"$(MAKE)" -f  "C__PROJECT.mk" clean
